apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - rbac-sandbox.yaml
  - redis.yaml
  - billet.yaml
  - profiles.yaml
  - secret.yaml
  - hairpin.yaml
